### PR TITLE
Initial blog post content

### PR DESCRIPTION
**Pull request by jamesmunns**

### CODE REVIEW

**Comment by jamesmunns** [comment]
@therealprof re: drafts - no, I intend for this to go live as soon as this PR is merged, unlike the ongoing blog posts.

Re: the choice - We need to have some kind of default position, as the server is shutting down. It was discussed that IRC-to-IRC was the closest we could get to a "Status Quo". By providing a default choice, we hope to avoid a distinctly brexit-y exit of the mozilla IRC service.

I'm open to discussing this, but at the end of the day, I don't want us to be left with no consensus, and have the community be fractured to a number of different platforms.

**Comment by thejpster** [comment]
I'm happy without

**Comment by therealprof** [comment]
@jamesmunns There're two problems here: I don't think "Status Quo" is a goal worth achieving, especially when it's as terrible as this which is one of the reasons why Mozilla made this decision in the first place. Secondly the bar to overrule that behind-close-doors decision (which did not even include the majority of WG members, I should add) is so high that it's pretty much set in stone: There's no way any proposal can ever reach real consensus since the interests are just too diverse and on the other hand the request to propose an alternative with full discussion is so much work (not just writing it up but also defending it against the FUD storm) and comes with so minuscule chance for success that I don't expect it to happen; I certainly wouldn't waste my time and nerves on such a hopeless endeavour.

The only proper way to play this is to propose a couple of alternatives which would technically work and let the community vote.

**Comment by jamesmunns** [comment]
@therealprof are you willing to lead this effort? If so, I would appreciate you PRing this PR with your proposed plan. We can put this revision up for discussion at the next meeting, and hopefully have the WG vote for either the current plan (IRC to IRC), or the voting strategy you are proposing, within the next week.

**Comment by jamesmunns** [comment]
@therealprof Are you still interested in following up with this? It would be good to have your proposal so we can discuss in the next meeting tomorrow.

**Comment by therealprof** [comment]
@jamesmunns For me it's a matter of finding an hour or two to squeeze it in. Schedules are really tight ATM.

**Comment by therealprof** [comment]
@jamesmunns Here you go: https://github.com/rust-embedded/wg/issues/349

**Pull request merged**
