### PR TITLE
Add the updates of the showcase

### PR DESCRIPTION
**Pull request by TeXitoi**

### CODE REVIEW

**Comment by therealprof** [comment]
@TeXitoi I don't think it makes sense to change previous entries as only few people will notice the chance. Time to start a new one.

**Comment by TeXitoi** [comment]
Strange. As I can't see the newsletter 18 on the blog, I was thinking that it's the work in progress.

**Comment by therealprof** [comment]
Hm, yeah the last one was kinda out-of-order. We're getting really bad at this. 😞

**Comment by therealprof** [comment]
Let's see whether we can finish up this one and get it out of the door.

**Pull request merged**
