### PR TITLE
added obstacle avoiding robot to the NL!

### PR DESCRIPTION
**Pull request by Dajamante**

### CODE REVIEW

**Review by hargoniX — APPROVED** [review]
The force push probably made my review invalid

**Review by eldruin — APPROVED** [review]
Awesome, thanks!

bors r+

**Comment by Dajamante** [comment]
> The force push probably made my review invalid

Hi again, what did you mention? I did a force push because I amended my commit. I did not know things would disappear.

**Comment by eldruin** [comment]
@Dajamante don't worry, that is just how GitHub review works. Since you amended your commit after a review was added, GitHub dismissed the previous review because what was reviewed actually changed. The review did not disappear, just the review status of this PR was reset.
Amending the commit was the right thing to do.

**Pull request merged**
