### PR TITLE
Add new blog posts and crates originating from drogue

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by jamesmunns** [comment]
Hey @lulf, could you drop the indent level (the leading four spaces mess up the formatting), and move your news item under the two examples?

Thanks for submitting!

**Comment by lulf** [comment]
@jamesmunns Sorry about that. Fix attempted. How do i get the next newsletter to show up running zola serve?

**Comment by jamesmunns** [comment]
@lulf I think you just need to change the `draft = true` in the frontmatter, and make sure the publish data is <= the current date.

**Review by jamesmunns — APPROVED** [review]
Looks great, thanks for the fix!

bors r+

**Pull request merged**
