### PR TITLE
Postpone as we've caught up

### PR DESCRIPTION
**Pull request by jamesmunns**
Hey @rust-embedded/resources, I think we've caught up, so I'd propose we postpone the next article to 1month after the last one. Let me know if this works for you!

### CODE REVIEW

**Comment by jamesmunns** [comment]
Also CC @kalkyl and @hargoniX

**Review by eldruin — APPROVED** [review]
Sounds good to me. Thanks!

**Review by hargoniX — APPROVED** [review]
To me as well

**Comment by therealprof** [comment]
Hm, the date is very far out. I was hoping we could go back to a 2 weeks cadence. In order to get more contributions we might want to advertise this maybe a bit more.

**Comment by cecton** [comment]
Fine by me as I missed the previous one and I will have the last part of my adventures this weekend.

**Comment by andre-richter** [comment]
Seems we need a decision here. Approvals came in before @therealprof chimed in.
@jamesmunns any thoughts about his proposal?

**Comment by therealprof** [comment]
It really doesn't matter anyway what date we put tentatively into the draft.

I'd still say we should try to aim for a consistent and shorter timeframe and probably release the next one much quicker than end of September.

bors r=eldruin

**Pull request merged**
