### PR TITLE
Update 2020-08-24-newsletter-25.md

### PR DESCRIPTION
**Pull request by therealprof**

### CODE REVIEW

**Review by eldruin — DISMISSED** [review]
Great stuff, thanks!
I also have a couple f411 pills. They are definitely worth it.

bors r+

**Comment by eldruin** [comment]
@therealprof could you resolve the conflict?

**Comment by therealprof** [comment]
Done. It's a bit unfortunate that every one will fiddle with the same line in the link block and so cause merge conflict after merge conflict. I wonder whether we can improve that.

**Review by eldruin — APPROVED** [review]
Yes, I do not know how we would avoid this, other than having one central person add the entries, but that adds work on our side.

bors r+

**Pull request merged**
